from __future__ import annotations

import struct

MAGIC = b"FUDP"
VERSION = 2

MSG_HELLO = 1
MSG_CHALLENGE = 2
MSG_PROVE = 3
MSG_ACK = 4
MSG_REQUEST = 5
MSG_RESPONSE = 6
MSG_ERROR = 7
MSG_PING = 8
MSG_PONG = 9
MSG_FRAME_ACK = 10
MSG_PATH_CHALLENGE = 11
MSG_PATH_RESPONSE = 12
MSG_CLOSE = 13

FLAG_ENCRYPTED = 1 << 0
FLAG_RESPONSE = 1 << 1
FLAG_ERROR = 1 << 2
FLAG_COMPRESSED = 1 << 3
FLAG_0RTT = 1 << 4
FLAG_MIGRATED = 1 << 5

MAX_PACKET_SIZE = 4096
MAX_PATH_BYTES = 512
MAX_BODY_BYTES = 1024 * 1024
MAX_CLIENT_ID_BYTES = 128
MAX_TICKET_BYTES = 512

MAX_PENDING_TTL = 30.0
MAX_SESSION_TTL = 300.0
MAX_CLOCK_SKEW = 15
REPLAY_WINDOW = 64
DEFAULT_TIMEOUT = 2.0
DEFAULT_RETRIES = 3
DEFAULT_RATE = 800.0
DEFAULT_BURST = 1600.0
DEFAULT_STREAM_LIMIT = 1024
DEFAULT_RESPONSE_CACHE_TTL = 30.0
DEFAULT_PATH_VALIDATION_TTL = 10.0
DEFAULT_RESUMPTION_TTL = 3600.0

HEADER_STRUCT = struct.Struct("!4sBBH Q I I I H I")
HEADER_SIZE = HEADER_STRUCT.size

METHOD_NONE = 0
METHOD_GET = 1
METHOD_POST = 2
METHOD_PUT = 3
METHOD_DELETE = 4
METHOD_PATCH = 5

METHOD_NAMES = {
    METHOD_NONE: "NONE",
    METHOD_GET: "GET",
    METHOD_POST: "POST",
    METHOD_PUT: "PUT",
    METHOD_DELETE: "DELETE",
    METHOD_PATCH: "PATCH",
}
METHOD_CODES = {value: key for key, value in METHOD_NAMES.items()}
